name: Gerar APK Vs Autoatendimento 

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar arquivos do repositório
        uses: actions/checkout@v4

      - name: Preparar projeto Android
        run: |
          unzip -o Vs_Autoatendimento_v11.zip
          cd vila_android
          echo "Projeto preparado"

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.7'

      - name: Compilar APK
        run: |
          cd vS_android
          gradle assembleDebug

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: VS-Autoatendimento-APK
          path: vS_android/app/build/outputs/apk/debug/app-debug.apk
